artifacts_root: artifacts


data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/FBrownp/ML-geo/main/notebook/main_data.csv
  local_data_file: artifacts/data_ingestion/main_data.csv

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/main_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  STATUS_FILE_DTYPE: artifacts/data_validation/status_dtype.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/main_data.csv
  transformation_path: artifacts/data_transformation/transformation.pkl