artifacts_root: artifacts


data_ingestion: 
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/FBrownp/ML-geo/blob/main/notebook/main_data.csv
  local_data_file: artifacts/data_ingestion/main_data.csv