name: Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'Dockerfile'
      - 'template.py'
      - 'setup.py'

jobs: 
  Integration: 
    name: Continous Integration
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  Verification:
    name: Run DVC pipeline
    runs-on: windows-latest
    steps:

      - uses: actions/checkout@v3
      
      - name: Install DVC
        shell: bash
        run: | 
        pip install -r requirements.txt
        dvc pull --run-cache
        dvc repro
        dvc push

      - name: Commit changes in dvc.lock
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Commit changes in dvc.lock
          branch: main
          file_pattern: dvc.lock