name: Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'Dockerfile'
      - 'template.py'
      - 'setup.py'

jobs: 
  Integration: 
    name: Continous Integration
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  Verification:
    name: Run DVC pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Pull data from DVC
        run: 
          dvc remote modify origin --local auth basic 
          dvc remote modify origin --local user ${{ secrets.DAGSHUBUSERNAME }}
          dvc remote modify origin --local password ${{ secrets.DAGSHUBKEY }}
          dvc pull

      - name: Run the pipeline
        run: dvc repro

      - name: Push the outcome to DVC remote storage
        run: dvc push

      - name: Commit changes in dvc.lock
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Commit changes in dvc.lock
          branch: main
          file_pattern: dvc.lock