name: Workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'Dockerfile'
      - 'template.py'
      - 'setup.py'

jobs: 
  Integration: 
    name: Continous Integration
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  Verification: 
    - name: Run the code
      uses: ML-GEO
      run: python dvc.yaml